### ISSUE TITLE
A fresh install fails.

### ISSUE THREAD

**Issue by ramanpreetnara** [quandl/ember-velocity-mixin#7]
https://github.com/ramanpreetnara/velocity-failure

The steps I followed to install were:
```
$ ember install:addon ember-velocity-mixin
```

Running the application:
```
$ ember serve
```

The attached project fails with the following error:
```bash
Cannot read property 'velocityOptions' of undefined
TypeError: Cannot read property 'velocityOptions' of undefined
    at Class.included (/home/ramanpreet/workspace/ember/velocity-failure/node_modules/ember-velocity-mixin/node_modules/ember-cli-velocity/index.js:19:35)
    at /home/ramanpreet/workspace/ember/velocity-failure/node_modules/ember-cli/lib/models/addon.js:211:32
    at Array.map (native)
    at Class.eachAddonInvoke (/home/ramanpreet/workspace/ember/velocity-failure/node_modules/ember-cli/lib/models/addon.js:209:22)
    at Class.Addon.included (/home/ramanpreet/workspace/ember/velocity-failure/node_modules/ember-cli/lib/models/addon.js:315:8)
    at EmberApp.<anonymous> (/home/ramanpreet/workspace/ember/velocity-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:277:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/home/ramanpreet/workspace/ember/velocity-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:272:45)
    at new EmberApp (/home/ramanpreet/workspace/ember/velocity-failure/node_modules/ember-cli/lib/broccoli/ember-app.js:236:8)
    at Object.<anonymous> (/home/ramanpreet/workspace/ember/velocity-failure/Brocfile.js:5:11)
``` 

Is there something really obvious I'm missing?

**Comment by jbyck** [comment]
Sorry, this project is now maintained here: https://github.com/embersherpa/ember-velocity-mixin.  I will update the README.
